### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nicozorza** [paukstelis/Octoprint-Cancelobject#1]
Good afternoon. I recentely tested your code but I couldn't make it work. I used Simplify3D to create two dummy pieces in two differente processes, but when I cancelled one of the processes, both of them kept printing.
I'm currentely using OctoPrint 1.3.8 and Simplify3D 4.0.1.
Thank you in advance.
Nicolás Zorzano.

**Comment by paukstelis** [comment]
Please install the most recent version and provide your octoprint.log file for when the object is cancelled and when it hits a skipped object. Additionally, it would be helpful to provide the S3D factory file and/or gcode.

**Comment by CNCKitchen** [comment]
Unfortunately it doesn't work for me either. The 3 processes are recognized and I can cancle them, but nothing happens. Also noticed that the statusbar always shows NONE:
![2018-06-10 14_05_53-octoprint](https://user-images.githubusercontent.com/11601966/41201405-a8d3fbce-6cb7-11e8-81c6-52c7d7064ff5.png)
Here are the settings (nothing altered):
![2018-06-10 14_06_10-octoprint](https://user-images.githubusercontent.com/11601966/41201421-e2ddc890-6cb7-11e8-846d-aef2dd1ef389.png)
And here a GCODE snippet:
![2018-06-10 14_06_38-c__users_stefa_desktop_kingmarvin_2 gcode - notepad](https://user-images.githubusercontent.com/11601966/41201422-e8d0a5ec-6cb7-11e8-8cae-32ac9643c122.png)

**Comment by CNCKitchen** [comment]
The lines seem to be replaced in the G-Code but still all the parts keep printing, when I cancel them:
![2018-06-10 17_29_57-c__users_stefa_downloads_kingmarvin_1 gcode - notepad](https://user-images.githubusercontent.com/11601966/41203198-0a267a98-6cd4-11e8-834c-b37e693ba647.png)
I'd love to get this working!

**Comment by paukstelis** [comment]
Can you provide your octoprint.log file? This will be helpful for debugging.

**Comment by CNCKitchen** [comment]
Of course, here you go:
[octoprint.log](https://github.com/paukstelis/Octoprint-Cancelobject/files/2088009/octoprint.log)

**Comment by paukstelis** [comment]
Thanks. This behavior seems odd since it should never reach that point with a None object. You might try changing the object replacement tag to something else or just retyping it and then saving (followed by restarting octoprint). Also, you may want to turn off your timelapse since it is generating errors that make it difficult to look through the log. Not sure if it matters, but can you provide some more details about the server running octoprint? RaspPi, etc.?

**Comment by paukstelis** [comment]
Also, if you make the object replacement tag something else, you will need to re-upload the gcode file.

**Comment by CNCKitchen** [comment]
Unfortunately still doesn't work. I attached another log (camera disabled ;-) )
[octoprint (2).log](https://github.com/paukstelis/Octoprint-Cancelobject/files/2088137/octoprint.2.log)

**Comment by paukstelis** [comment]
Thanks again. It does seem that for whatever reason the main object list is getting lost. If you could, delete the plugin and install it from this URL: https://github.com/paukstelis/Octoprint-Cancelobject/archive/debugging.zip using the plugin manager. This just has some more logging information to see what is happening. You might also try connecting to the virtual printer included in octoprint so you don't actually have to keep starting prints!

**Comment by CNCKitchen** [comment]
Here you go:
[octoprint (3).log](https://github.com/paukstelis/Octoprint-Cancelobject/files/2088172/octoprint.3.log)

**Comment by paukstelis** [comment]
Great. I think I see the issue. Just need to figure out how to deal with it.

**Comment by paukstelis** [comment]
Please reinstall the debugging branch again and see if that works. If not, please provide me your gcode so I can test locally.

**Comment by paukstelis** [comment]
Or simpler yet, just change the Object Regular expression line to be: `; process (.*)\s`

**Comment by CNCKitchen** [comment]
Unfortunately still doesn't work. Here is the log and the GCode file:
[octoprint (4).log](https://github.com/paukstelis/Octoprint-Cancelobject/files/2088209/octoprint.4.log)

[KingMarvin_5gcode.txt](https://github.com/paukstelis/Octoprint-Cancelobject/files/2088210/KingMarvin_5gcode.txt)
Thank you very much for your efforts!

**Comment by paukstelis** [comment]
OK! I think I have it worked it. It was due to a carriage return being included  in the object name when the file was re-written. I have it working with your gcode on my end. Please reinstall debugging branch and test it there. I'll push this into the master if it works, but it highlights some other things I hadn't considered that I need to work on. Thank you very much for helping me work this out.

**Comment by CNCKitchen** [comment]
Works now! Thank you very much for your support.

**Comment by paukstelis** [comment]
@CNCKitchen made a nice youtube video long ago. I'm closing after 2+ years!
