### ISSUE TITLE
new functionality

### ISSUE THREAD

**Issue by sagatxxx** [paukstelis/Octoprint-Cancelobject#12]
It would be interesting to implement the function that when a process ends and the next and last one has been canceled it executes the finalization scripts because if it does not feel like this:

https://imgur.com/a/myCYY3N

thanks a lot

**Comment by paukstelis** [comment]
See the instructions. Just add `; process ENDGCODE` at the beginning of your end gcode script (assuming you are using S3D). This will make sure that the script gcode gets executed.

**Comment by sagatxxx** [comment]
ok, that clueless I am! thanks, good work
