### ISSUE TITLE
Duet web control

### ISSUE THREAD

**Issue by Patrik-svobodik** [paukstelis/Octoprint-Cancelobject#14]
Hi, would you write this for DWC? It is the only missing feature on the DWC

**Comment by paukstelis** [comment]
I'm not at all familiar with DWC, but I can give it a shot if someone wants to send me a Duet Wifi to test with.

**Comment by Patrik-svobodik** [comment]
Contact @dc42
po 8. 10. 2018 v 2:13 odesílatel paukstelis <notifications@github.com>
napsal:
