### ISSUE TITLE
Can not update to new version.. 0.2.1

### ISSUE THREAD

**Issue by Stady234** [paukstelis/Octoprint-Cancelobject#16]
Updating...
Updating, please wait.
+++++++++++++++++++++++++++++++++++
Now updating Cancel object to 0.2.1
+++++++++++++++++++++++++++++++++++
/home/pi/oprint/bin/python2 -m pip install https://github.com/you/OctoPrint-Cancelobject/archive/0.2.1.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/you/OctoPrint-Cancelobject/archive/0.2.1.zip
HTTP error 404 while getting https://github.com/you/OctoPrint-Cancelobject/archive/0.2.1.zip
Could not install requirement https://github.com/you/OctoPrint-Cancelobject/archive/0.2.1.zip because of error 404 Client Error: Not Found for url: https://github.com/you/OctoPrint-Cancelobject/archive/0.2.1.zip
Could not install requirement https://github.com/you/OctoPrint-Cancelobject/archive/0.2.1.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/you/OctoPrint-Cancelobject/archive/0.2.1.zip for URL https://github.com/you/OctoPrint-Cancelobject/archive/0.2.1.zip
The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.

**Comment by paukstelis** [comment]
It was a simple fix, but unfortunately, you'll need to uninstall/reinstall the plugin. Future versions won't have this issue.

**Comment by Stady234** [comment]
Awesome, got everything reinstalled!  Thanks!
