### ISSUE TITLE
Extrusion issue after cancelling

### ISSUE THREAD

**Issue by Semme** [paukstelis/Octoprint-Cancelobject#25]
Hey there, 

the last 2 days I was trying to get this plugin to work. The setup isn't a problem. But, if you cancel an object during the print, all other objects will be overextruded from that moment on. It doesn't matter how many object there are. 

Picture:
https://abload.de/img/img_0126jbk2k.jpg

My Setup:
DIY Printer with E3D V6 + Bondtech Bowden setup.
Simplify3D 4.0
Octoprint 1.3.10
Marlin (near current version)
45mm/s, 0,2mm layer, individual identical processes

I already tried absolute and relative extrusion.

Would be happy for any help. Thanks a lot for your great work!

**Comment by paukstelis** [comment]
It would be most useful if you could supply your gcode. My first guess is that you are  not using Z-hopping on retracts. If not, you want to look into including the appropriate command in the "Allowed GCODE" setting to make sure that any Z-height changes in cancelled objects are respected.

**Comment by Semme** [comment]
You are right. I do not have z-lift for retractions enabled. Is that necessary? 

Also which command should I try to include in the "allowed" gcode"?

I attached my gcode. Also included is a version with zhop enabled, which i will test now. 

[S3D_test.zip](https://github.com/paukstelis/Octoprint-Cancelobject/files/2889593/S3D_test.zip)

**Comment by paukstelis** [comment]
Yes, based on your gcode, just putting `G1 Z.*` in the Allowed GCODE setting should allow it to work without having z-hop enabled.

**Comment by paukstelis** [comment]
Also, I highly recommend that you include `; ENDGCODE` at the beginning of your end gcode script in S3D. This makes sure that if you skip the last object to be printed that your end script will still be run.

**Comment by Semme** [comment]
Works great now, thank you very much! :)
