### ISSUE TITLE
Cura[3.6.0] order of auto-arranged models

### ISSUE THREAD

**Issue by JLIspace** [paukstelis/Octoprint-Cancelobject#26]
Hey,
I just tried it the first time (after a had to stop a pretty long print because of one small part 😐). And as it turns out it works great! The only thing I had to change inside cura was relative extrusion as someone pointed out already (I guess, haven't tried it otherwise).
My only 'problem' is that I can't really differentiate a lot of (auto arranged) copys of the same stl file. Cura just tags them as "xxx.stl (1)", "xxx.stl (2)". I thought that this would happen in the order of printing, but that's not the case - at least for me.

So is there any easier way of spotting the right (already broken part) to cancle, without having to wait until the "red box" will appear just seconds before the printer is going to crash into it again?

Regards! :)

**Comment by paukstelis** [comment]
This will be addressed in latest version that will be out (hopefully) next week. It will provide markers in the gcodeviewer that you can use to cancel objects directly. Right now I am just trying to make it compatible with the ExcludeRegion plugin.

**Comment by JLIspace** [comment]
Oh, okay. That sounds awesome! 👍

**Comment by paukstelis** [comment]
New version has been released that allows cancelling from gcodeviewer. Please let me know how it works for you.

**Comment by JLIspace** [comment]
That's way better! There is no need to think about the order anymore.
Additionally, you could show the file names in the "Are you sure?" window so you can cancel similar looking (but different) models when you change your mind afterwards.
This would also remove the chance of aborting the wrong model due to tight spacing or wrong selection.

Thanks for the update!

**Comment by paukstelis** [comment]
yeah, adding object name in the pop-up should be pretty straightforward. I'll add that to the TODO for the next release.

**Comment by paukstelis** [comment]
You can try out the feature in the 0.3.2 branch. Install from octoprint via this url: https://github.com/paukstelis/Octoprint-Cancelobject/archive/0.3.2.zip
