### ISSUE TITLE
Latest 0.3.1 and no objects to see

### ISSUE THREAD

**Issue by chrisboer** [paukstelis/Octoprint-Cancelobject#29]
Work with latest Octoprint version on Prusa but don't see any objects when printing ?

**Comment by paukstelis** [comment]
Need a bit more information. What slicer are you using?

**Comment by chrisboer** [comment]
Slic3r 1.41.2 Prusa Edition

**Comment by paukstelis** [comment]
That explains it. You need to use 1.42 beta. In the output settings check the "label objects".

**Comment by chrisboer** [comment]
Thanks will give it a look ...

**Comment by chrisboer** [comment]
Yes it works with beta 1.42 of prusa slicer
