### ISSUE TITLE
Canceling first model freezes print

### ISSUE THREAD

**Issue by Atomsk102** [paukstelis/Octoprint-Cancelobject#31]
If I cancel the first model in the list, then at the beginning of the next layer, the printer freezes.  The head doesn't move, and the heaters stay on.

This may be a conflict with Octolapse, which takes control of the printer at the beginning of each layer, to move the head out of the way, for a snapshot.

**Comment by paukstelis** [comment]
What is in the terminal when it freezes?

**Comment by Atomsk102** [comment]
Terminal contents in attached text file.  I've also included the Gcode file that was running at the time.
[CE3_Cube Test.gcode.txt](https://github.com/paukstelis/Octoprint-Cancelobject/files/3082304/CE3_Cube.Test.gcode.txt)
[Terminal Dump.txt](https://github.com/paukstelis/Octoprint-Cancelobject/files/3082306/Terminal.Dump.txt)

When I try to cancel the print, The terminal says:

Changing monitoring state from "Printing" to "Cancelling"[...]

Communication timeout while printing, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.

**Comment by paukstelis** [comment]
Switch to relative extrusion in your slicer. It simplifies things greatly. I have absolute extrusion working OK on my printer, but its something that I've seen enough inconsistencies to not recommend it.

You are right it probably is related to OctoLapse. Can you try disabling OctoLapse and trying again?
