### ISSUE TITLE
File section

### ISSUE THREAD

**Issue by buliwyf42** [paukstelis/Octoprint-Cancelobject#34]
When i install the cancel Objects Plugin the files Section on the left gehts out of shape.
This is how it looks like if i disable the plugin: 
<img width="371" alt="Screenshot 2019-06-03 at 14 56 45" src="https://user-images.githubusercontent.com/4658822/58858547-08191500-86a8-11e9-933b-246d99d00cbd.png">
And this is how it looks like if i enable it. 
<img width="422" alt="Screenshot 2019-06-03 at 13 55 16" src="https://user-images.githubusercontent.com/4658822/58858548-08191500-86a8-11e9-906f-af4c28db9483.png">
I have the Version 0.3.1

**Comment by paukstelis** [comment]
I don't see that behavior, but I'll look into it. What other plugins do you have installed?

**Comment by buliwyf42** [comment]
Several, but i disabled nearly all of them to figure it out. I just let some originals plugins from foosel enabled.

**Comment by paukstelis** [comment]
Can you install from here: https://github.com/paukstelis/Octoprint-Cancelobject/archive/0.3.2.zip and see if this makes any difference?

**Comment by buliwyf42** [comment]
This looks definitely better
better. 
<img width="399" alt="Screenshot 2019-06-05 at 07 16 17" src="https://user-images.githubusercontent.com/4658822/58931912-e2e8dd00-8761-11e9-870c-afcc7d57a3df.png">

**Comment by paukstelis** [comment]
OK. I will put this out along with some other bug fixes in a new release. Thank you for reporting.
