### ISSUE TITLE
Upload to octoprint "watched" directory?

### ISSUE THREAD

**Issue by bluegizmo83** [paukstelis/Octoprint-Cancelobject#35]
"If you upload files directly to your octoprint instance, direct them to the watched directory and not the upload directory."

How exactly is this done?? I can't find any information about how to direct all uploads to the Watched DIR in octoprint... I can see that a DIR named "Watched" exists, but I can't figure out how I'm suppose to get my files to upload to there when I hit "Print with Octoprint" in CURA 4.0

**Comment by paukstelis** [comment]
It should work fine without modification using the Cura Octoprint Plugin. You can confirm by uploading a file to octoprint from Cura and seeing if the objects get loaded in the CancelObject tab.

**Comment by Haprog** [comment]
What about with PrusaSlicer? Should it work when I "upload" or "upload & print" directly from PrusaSlicer?

Would still be nice to know when and how to use the watched directory.
