### ISSUE TITLE
Cannot run on RPi Zero

### ISSUE THREAD

**Issue by wezzix** [paukstelis/Octoprint-Cancelobject#39]
I would like to note that I failed to have it running on RPi Zero, and this should maybe be mentioned in the description. Quite possibly, it is not powerful enough for this plugin.
I get an error usually around 5 minutes into the print such as this:

Error:Line Number is not Last Line Number+1, Last Line: 203 Resend: 204

Immediately after uninstalling the plugin, my prints began to succeed again.

**Comment by paukstelis** [comment]
RPi Zero is not recommended hardware for octoprint. Closing.
