### ISSUE TITLE
"homepage" link on OctoPrint plug-in page not correct

### ISSUE THREAD

**Issue by SpectreGadget** [paukstelis/Octoprint-Cancelobject#4]
Is "https://github.com/you/OctoPrint-Cancelobject"
Needs to be "https://github.com/paukstelis/Octoprint-Cancelobject"

**Comment by paukstelis** [comment]
Hmm..seemed OK to me:
![screenshot from 2018-06-14 07-32-36](https://user-images.githubusercontent.com/28326982/41409744-3ed29afa-6fa5-11e8-9211-620cbb158147.png)

I did notice that it was incorrect in setup.py. It has been corrected.

**Comment by SpectreGadget** [comment]
I removed and re-installed the plug-in and it was corrected.  Thanks
