### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by AnnabellaRenee87** [paukstelis/Octoprint-Cancelobject#48]
Can python 3 compatibility be added?

**Comment by paukstelis** [comment]
It is python 3 compatible. I just need to look into setting the appropriate flags.

**Comment by paukstelis** [comment]
Actually, @gdombiak added this some time back, so it should be python 3 ready.

 __plugin_name__ = "Cancel Objects"
__plugin_pythoncompat__ = ">=2.7,<4"

**Comment by paukstelis** [comment]
Pull request issued to mark as compatible.

**Comment by paukstelis** [comment]
PR accepted. Closing.
