### ISSUE TITLE
[Feature Request] Store settings

### ISSUE THREAD

**Issue by KenLucke** [paukstelis/Octoprint-Cancelobject#53]
A settings preference to store the latest setting of "Toggle Markers" so that it doesn't always default to "On" - it even resets (annoyingly) after every time I switch to another tab and back.

Or perhaps the option 
```
Default Markers Setting
[ ] On 
[ ] Off
[ ] Last Used
```

**Comment by paukstelis** [comment]
This will included in 0.4.2 in a simple form (default to on/off). Closing.

**Comment by KenLucke** [comment]
> This will included in 0.4.2 in a simple form (default to on/off). Closing.

Thank you.
