### ISSUE TITLE
After having paused a print this plugin no longer works.

### ISSUE THREAD

**Issue by alex050478** [paukstelis/Octoprint-Cancelobject#59]
After having paused a print (because filament ran ou) i can no longer cancel any objects. Anyone else having this issue?

**Comment by paukstelis** [comment]
I don't think I've run into this scenario before, but I will test it out and see what happens.

**Comment by paukstelis** [comment]
I did a quick test and didn't see anything weird after pausing and resuming. Can you provide some screenshots of what happens when you do this?
