### ISSUE TITLE
[Enhancement] Add clustering algorithm to detect different parts

### ISSUE THREAD

**Issue by JackToaster** [paukstelis/Octoprint-Cancelobject#6]
Currently, this plugin only works when the gcode is annotated by the slicer to indicate different parts.
I propose using a clustering algorithm to detect different parts and automatically annotate the gcode before printing.
[Here](http://scikit-learn.org/stable/modules/clustering.html#dbscan) is an example of such a clustering algorithm.
This would require parsing the gcode to acquire a list of 4d points (X,Y,Z,time/index) then running a clustering algorithm to split the points into parts, then annotating the gcode.
I'm going to start trying to split gcode files into points as soon as I get a chance, then I'll share my results.

**Comment by paukstelis** [comment]
Sounds interesting. I would think you would just want to cluster extrusion moves to simplify things a bit. The first big hurdle I see is that all Slicers have different ways of dealing with extrusion distances which could make things complicated. Looking forward to seeing how it works out.

**Comment by TTN-** [comment]
Extrusion distances are either relative or absolute.

I think you could consider a string of moves to be part of a cluster until negative movement is made on the E axis? It could get complicated with settings like retract on layer change, and retracts required that are part of the same object.

**Comment by paukstelis** [comment]
Closing as I am not going to look into this.
