### ISSUE TITLE
S3D Setup Explanation Please

### ISSUE THREAD

**Issue by Psyc0Flyer** [paukstelis/Octoprint-Cancelobject#7]
It would be nice to have a write-up or tutorial vid on how to "Create one process for each object or group of models you want to be able to cancel. Assign models to processes" with S3D.

**Comment by paukstelis** [comment]
Here you go. There really isn't much to it.
https://youtu.be/daFpISbwzt4

**Comment by paukstelis** [comment]
This is covered in the video and in instructions. And does anyone still use S3D? Closing.
