### ISSUE TITLE
Plugin menu completely blank

### ISSUE THREAD

**Issue by charminULTRA** [paukstelis/Octoprint-Cancelobject#75]
Plugin tab is completely blank in OctoPi during print, making it unusable.
![Screenshot 2023-03-15 084428](https://user-images.githubusercontent.com/29433007/225312540-5c20fb09-162d-4520-9731-9a85d52d39d5.png)

**Comment by charminULTRA** [comment]
![Screenshot 2023-03-15 08451f2](https://user-images.githubusercontent.com/29433007/225313049-8f74083e-5cd6-46c6-ba65-62a8b8e6f473.png)

**Comment by paukstelis** [comment]
1. The standard gcode viewer must be enabled for the plugin to work
2. Some UI modifier plugins are known to have issues with the plugin. Which one are you using?

**Comment by charminULTRA** [comment]
> 1. The standard gcode viewer must be enabled for the plugin to work
> 
>     2. Some UI modifier plugins are known to have issues with the plugin. Which one are you using?

Must be the gcode viewer, I got rid of it yesterday because I never use it. Sorry about that, thanks!
